json.extract! workflow_run,
              :id,
              :name,
              :description,
              :status,
              :created_at,
              :updated_at,
              :project_id,
              :current_step_id,
              :last_step_id
